apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-virtual-host-ingress-green
spec:
  rules:
  - host: sandbox1320.opentlc.com
    http:
      paths:
      - backend:
          serviceName: green-nginx-service
          servicePort: 8080
